services:
  postgres:
    image: postgres
    container_name: planitapp-dev

    environment:
      POSTGRES_USER: planitapp
      POSTGRES_PASSWORD: planitapp
      POSTGRES_DB: planitapp

    ports:
      - "5432:5432"

    volumes:
      - planitapp_data:/var/lib/postgresql

volumes:
  planitapp_data: